

import React from 'react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const TermsOfUseModal: React.FC<LegalModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 bg-gray-900/80 flex items-center justify-center z-[110] p-4 animate-fadeIn"
      aria-modal="true"
      role="dialog"
      onClick={onClose}
    >
      <div
        className="bg-gray-800 p-6 rounded-lg shadow-xl max-w-3xl w-full border border-gray-700 max-h-[90vh] flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        <div className="flex justify-between items-center pb-4 border-b border-gray-600 flex-shrink-0">
          <h2 className="text-xl font-bold text-yellow-400">Terms of Use</h2>
          <button onClick={onClose} className="p-1 rounded-full text-gray-400 hover:text-white">&times;</button>
        </div>
        <div className="prose prose-sm prose-invert max-w-none text-gray-300 mt-4 overflow-y-auto pr-2">
            <p><em>Last Updated: {new Date().toLocaleDateString()}</em></p>
            <p>By accessing or using Chart Oracle ("the Service"), you agree to be bound by these Terms of Use ("Terms").</p>

            <h4>1. Acceptance of Terms</h4>
            <p>You must agree to these Terms to use the Service. By creating an account or using the Service, you represent that you have read, understood, and agree to be bound by these Terms.</p>
            
            <div className="bg-red-900/30 border border-red-500/50 p-4 rounded-md my-4">
                <h4 className="!text-red-300 !mt-0">2. Not Financial Advice (NFA) Disclaimer</h4>
                <p className="!text-red-200"><strong>The Service does not provide financial, investment, or trading advice.</strong> All content, data, and analysis generated by the AI ("the Oracle") are for <strong>informational and educational purposes only</strong>. They are not, and should not be construed as, a recommendation, offer, or solicitation to buy, sell, or hold any financial instrument.</p>
                <p className="!text-red-200">Trading financial markets involves substantial risk of loss and is not suitable for every investor. You are solely responsible for your own investment and trading decisions. <strong>You should use the information provided by the Service for paper trading, backtesting, and skill development only.</strong> Never risk money that you cannot afford to lose. Always conduct your own research and consult with a qualified financial advisor before making any investment decisions.</p>
            </div>

            <h4>3. Description of Service</h4>
            <p>Chart Oracle is an AI-powered tool designed to assist users in analyzing trading charts for educational and practice purposes. The Service uses large language models to interpret data and provide potential trade scenarios based on user-selected strategies.</p>

            <h4>4. User Responsibilities</h4>
            <ul>
                <li>You agree to use the Service for lawful purposes only.</li>
                <li>You are responsible for maintaining the confidentiality of your Master Key and for all activities that occur under your session.</li>
                <li>You agree not to use the Service to make financial decisions with real capital. The Service is a simulated environment for learning.</li>
            </ul>

            <h4>5. Intellectual Property</h4>
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of its creators. User-provided data (saved trades, settings, etc.) remains the user's property, stored locally in their browser.</p>

            <h4>6. Limitation of Liability</h4>
            <p>In no event shall the creators of Chart Oracle be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>
            <p><strong>Your use of the Service is at your sole risk.</strong> The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind.</p>
            
            <h4>7. Termination</h4>
            <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

        </div>
         <div className="flex-shrink-0 pt-4 mt-auto border-t border-gray-600">
            <button onClick={onClose} className="w-full font-bold py-2 px-6 rounded-lg transition-colors bg-yellow-500 hover:bg-yellow-400 text-gray-900">
                Close
            </button>
        </div>
      </div>
       <style>{`
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        .animate-fadeIn { animation: fadeIn 0.2s ease-out; }
      `}</style>
    </div>
  );
};

export default TermsOfUseModal;